server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  logger:
    path:    "logs/sql"
    level:   "all"

  default:
    link:   "mysql:root:2332@tcp(172.17.0.2:3306)/gym"
    debug:  true

