server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  logger:
    path:    "logs/sql"
    level:   "all"

  default:
    link:   "mysql:root:2332@tcp(172.250.0.233:3306)/gym"
    debug:  true

upload:
  defaultAvatar: "default.png"
  path: "uploads/"

receipt:
  path: "receipts/"
  pdfPath: "receipts/pdf/"
  qrPath:  "receipts/qr/"