server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  logger:
    path:    "logs/sql"
    level:   "all"

  default:
    link:   "mysql:root:2332@tcp(172.250.0.233:3306)/gym?charset=utf8mb4&parseTime=True&loc=Local"
    debug:  true

upload:
  defaultAvatar: "default.png"
  path: "uploads/"

receipt:
  path: "receipts/"
  pdfPath: "receipts/pdf/"
  qrPath:  "receipts/qr/"

timeZone: "Asia/Shanghai"

# JUST ADD IT TO THE CUSTOM CONFIGURATION
customConfigUpdate: 1 # 0 - Dont update when start up
                      # 1 - Update when start up
customConfig:
  OpenTime: "08:00"
  CloseTime: "22:00"
