# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

services:
  - docker:20.10.12-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - deploy
format:
  image: golang:latest
  stage: test
  script:
    # - go fmt $(go list ./... | grep -v /vendor/)
    # - go vet $(go list ./... | grep -v /vendor/)
    # - go test -race $(go list ./... | grep -v /vendor/)
    - go test -v
compile:
  image: golang:latest
  stage: build
  script:
    # - mkdir -p mybinaries
    # - go build -o mybinaries ./...
    - make
    - gf build main.go
  artifacts:
    paths:
      - main
deploy:
  image: docker:stable
  stage: deploy
  script: 
    - echo "Delete previous container"
    - docker stop gym-demo
    - docker rm gym-demo
    - docker rmi gym_kneethaimay/gym-demo
    - echo "Deployment Todo"
    - make cli
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.cn,direct
    - make
    - cp manifest/config/config.prod.yaml manifest/config/config.yaml
    - gf docker -tn gym-demo -tp gym_kneethaimay
    - docker run -itd --name gym-demo -p "16800:8000" gym_kneethaimay/gym-demo
    - echo "Done"
  environment: production