// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "Gym-backend/internal/logic/bizctx"
	_ "Gym-backend/internal/logic/session"
)
