// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "Gym-backend/internal/logic/bizctx"
	_ "Gym-backend/internal/logic/facility"
	_ "Gym-backend/internal/logic/file"
	_ "Gym-backend/internal/logic/middleware"
	_ "Gym-backend/internal/logic/session"
	_ "Gym-backend/internal/logic/user"
)
