// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Course is the golang structure of table course for DAO operations like Where/Data.
type Course struct {
	g.Meta       `orm:"table:course, do:true"`
	ID           interface{} // ID
	STATUS       interface{} // status
	STARTTIME    *gtime.Time // start_time
	ENDTIME      *gtime.Time // end_time
	TITLE        interface{} // title
	DESCRIPTION  interface{} // course discription
	TEACHER      interface{} // teacher
	TYPE         interface{} // type
	PLACE        interface{} // place
	MAXMEMBERNUM interface{} // max member num
	NOWNUM       interface{} // now member num
}
