// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FacilityPlace is the golang structure of table facility_place for DAO operations like Where/Data.
type FacilityPlace struct {
	g.Meta      `orm:"table:facility_place, do:true"`
	ID          interface{} // ID
	FACILITYID  interface{} // Facility ID
	NAME        interface{} // Place Name
	DESCRIPTION interface{} // Place Description
	COST        interface{} // Place order code
}
