// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FacilityImage is the golang structure of table facility_image for DAO operations like Where/Data.
type FacilityImage struct {
	g.Meta     `orm:"table:facility_image, do:true"`
	Id         interface{} //
	Path       interface{} //
	UploadTime *gtime.Time //
	FacilityID interface{} //
}
