// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure of table order for DAO operations like Where/Data.
type Order struct {
	g.Meta      `orm:"table:order, do:true"`
	ID          interface{} // ID
	USERID      interface{} // User id
	PLACEID     interface{} // Place ID
	TIME        *gtime.Time // Order Time
	STARTTIME   *gtime.Time // Start time of the order
	ENDTIME     *gtime.Time // End time of the order
	PAYMENTTYPE interface{} // Payment type
	AMOUNT      interface{} // Amount of the order
	ORDERCODE   interface{} // Order code
}
