// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Payment is the golang structure of table payment for DAO operations like Where/Data.
type Payment struct {
	g.Meta      `orm:"table:payment, do:true"`
	ID          interface{} // ID
	WALLETID    interface{} // Wallet ID
	ORDERID     interface{} // Order ID
	PAYMENTCODE interface{} // Payment code
	TIME        interface{} // Payment Time
}
