// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Receipt is the golang structure of table receipt for DAO operations like Where/Data.
type Receipt struct {
	g.Meta      `orm:"table:receipt, do:true"`
	ID          interface{} // ID
	ORDERID     interface{} // Order Id
	RECEIPTPATH interface{} // PDF Receipt path
}
