// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Topics is the golang structure of table topics for DAO operations like Where/Data.
type Topics struct {
	g.Meta          `orm:"table:topics, do:true"`
	ID              interface{} // ID
	USERID          interface{} // USER_ID
	CONTENT         interface{} // content
	TITLE           interface{} // title
	UPDATETIME      *gtime.Time // time
	APPROVECOUNT    interface{} // Approve count
	DISAPPROVECOUNT interface{} // Disapprove count
	IMAGES          interface{} // Image urls
	VIDEOS          interface{} // Video urls
}
