// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicComment is the golang structure of table topic_comment for DAO operations like Where/Data.
type TopicComment struct {
	g.Meta          `orm:"table:topic_comment, do:true"`
	ID              interface{} // ID
	USERID          interface{} // USER_ID
	TOPICID         interface{} // TOPIC_ID
	PARENTCOMMENTID interface{} // Parent comment ID
	TITLE           interface{} // Comment_title
	CONTENT         interface{} // Comment_conrtent
	APPROVE         interface{} // comment_approve
	DISAPPROVE      interface{} // comment_disapprove
	UPDATETIME      *gtime.Time // creat_time
	IMAGES          interface{} // Image urls
}
