// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicApproves is the golang structure of table topic_approves for DAO operations like Where/Data.
type TopicApproves struct {
	g.Meta     `orm:"table:topic_approves, do:true"`
	ID         interface{} // ID
	USERID     interface{} // USER_ID
	TOPICID    interface{} // TOPIC_ID
	TYPE       interface{} // TYPE
	UPDATETIME *gtime.Time // create_time
}
