// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// TopicCommentApproves is the golang structure of table topic_comment_approves for DAO operations like Where/Data.
type TopicCommentApproves struct {
	g.Meta     `orm:"table:topic_comment_approves, do:true"`
	ID         interface{} // ID
	TYPE       interface{} // TYPE
	UPDATETIME interface{} // Update time
	USERID     interface{} // USER_ID
	COMMENTID  interface{} // topic_comment_ID
}
