// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	ID         interface{} // USER ID
	USERNAME   interface{} // USERNAME
	PASSWORD   interface{} // PASSWORD
	AVATAR     interface{} // AVATAR URL
	EMAIL      interface{} // EMAIL ADDRESS
	PHONE      interface{} // PHONE NUMBER
	GENDER     interface{} // GENDER
	CREATETIME *gtime.Time // CREATE AT
	ROLE       interface{} // ROLE
	LOGINTIME  *gtime.Time // LAST LOGIN TIME
}
