// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Wallet is the golang structure of table wallet for DAO operations like Where/Data.
type Wallet struct {
	g.Meta `orm:"table:wallet, do:true"`
	ID     interface{} // ID
	USERID interface{} // User ID
	AMOUNT interface{} // Money amount
	STATUS interface{} // Wallet status
}
