// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WalletCard is the golang structure of table wallet_card for DAO operations like Where/Data.
type WalletCard struct {
	g.Meta      `orm:"table:wallet_card, do:true"`
	ID          interface{} // ID
	BANKID      interface{} // Bank ID of the card
	WALLETID    interface{} // Wallet ID of the card
	CARDACCOUNT interface{} // Card number
	PHONE       interface{} // Phone of the card
	AMOUNT      interface{} // Amount in the card
}
