
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link:     "mysql:root:2332@tcp(172.17.0.2:3306)/gym"
        tables:   "user"
        jsonCase: "CamelLower"

