// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model/entity"
)

type (
	IFacility interface {
		GetFacilityList() (res []*entity.Facility, err error)
		GetFacilityById(id int) (res *entity.Facility, err error)
		GetFacilityByName(name string) (res *entity.Facility, err error)
		GetFacilityBySearch(search string) (res []*entity.Facility, err error)
	}
)

var (
	localFacility IFacility
)

func Facility() IFacility {
	if localFacility == nil {
		panic("implement not found for interface IFacility, forgot register?")
	}
	return localFacility
}

func RegisterFacility(i IFacility) {
	localFacility = i
}
