// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IFacility interface {
		GetFacilityList(ctx context.Context) (res []*model.FacilityEntity, err error)
		GetFacilityById(ctx context.Context, id int) (res *model.FacilityEntity, err error)
		GetFacilityByName(ctx context.Context, name string) (res *model.FacilityEntity, err error)
		GetFacilityBySearch(ctx context.Context, search string) (res []*model.FacilityEntity, err error)
		AddFacility(ctx context.Context, facility *entity.Facility) (err error)
		ModifyFacility(ctx context.Context, facility *entity.Facility) (err error)
		ValidateFacility(ctx context.Context, facility *entity.Facility) (err error)
		GetFacilityImages(ctx context.Context, id int) (res []*entity.FacilityImage, err error)
		FetchFacilityImages(ctx context.Context, facilities []*entity.Facility) (res []*model.FacilityEntity, err error)
	}
)

var (
	localFacility IFacility
)

func Facility() IFacility {
	if localFacility == nil {
		panic("implement not found for interface IFacility, forgot register?")
	}
	return localFacility
}

func RegisterFacility(i IFacility) {
	localFacility = i
}
