// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"context"
)

type (
	IPayment interface {
		CreatePayment(ctx context.Context, form *model.CreatePaymentForm) error
	}
)

var (
	localPayment IPayment
)

func Payment() IPayment {
	if localPayment == nil {
		panic("implement not found for interface IPayment, forgot register?")
	}
	return localPayment
}

func RegisterPayment(i IPayment) {
	localPayment = i
}
