// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"

	"github.com/gogf/gf/v2/os/gtime"
)

type (
	ISubscription interface {
		GetSubscriptionEndDayByUserId(ctx context.Context, userId int) (res *gtime.Time, err error)
		GetSubscriptionListByUserId(ctx context.Context, userId int) (res []*entity.Subscription, err error)
		CreateSubscription(ctx context.Context, form *model.CreateSubscriptionForm) error
		GenerateOrderCode() string
	}
)

var (
	localSubscription ISubscription
)

func Subscription() ISubscription {
	if localSubscription == nil {
		panic("implement not found for interface ISubscription, forgot register?")
	}
	return localSubscription
}

func RegisterSubscription(i ISubscription) {
	localSubscription = i
}
