// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IUser interface {
		Login(ctx context.Context, input model.UserLoginForm) error
		Register(ctx context.Context, input model.UserRegisterForm) error
		GetUserByUsernameAndPassword(ctx context.Context, username string, password string) (user *entity.User, err error)
		GetUserByID(ctx context.Context, id uint) (user *entity.User, err error)
		ValidateUsername(ctx context.Context, username string) error
		ValidateEmail(ctx context.Context, email string) error
		UpdateEmptyAvatarPath(ctx context.Context, user *entity.User) error
		UpdateAvatar(ctx context.Context, userId uint, avatar string) error
		GetCurrentUser(ctx context.Context) (user *entity.User)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
