// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IWallet interface {
		GetWallet(ctx context.Context) (wallet *entity.Wallet, err error)
		SetStatus(ctx context.Context, status int) error
	}
)

var (
	localWallet IWallet
)

func Wallet() IWallet {
	if localWallet == nil {
		panic("implement not found for interface IWallet, forgot register?")
	}
	return localWallet
}

func RegisterWallet(i IWallet) {
	localWallet = i
}
