// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Bank is the golang structure for table bank.
type Bank struct {
	ID   int    `json:"iD"   ` // ID
	NAME string `json:"nAME" ` // Bank name
}
