// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CommentResponse is the golang structure for table comment_response.
type CommentResponse struct {
	ID               int         `json:"iD"               ` // ID
	PARENTRESPONSEID int         `json:"pARENTRESPONSEID" ` // PARENT_RESPONSE_ID
	Title            string      `json:"title"            ` // title
	Content          string      `json:"content"          ` // content
	USERID           int         `json:"uSERID"           ` // USER_ID
	CreatTime        *gtime.Time `json:"creatTime"        ` // creat_time
}
