// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Course is the golang structure for table course.
type Course struct {
	ID           int         `json:"iD"           ` // ID
	STATUS       int         `json:"sTATUS"       ` // status
	STARTTIME    *gtime.Time `json:"sTARTTIME"    ` // start_time
	ENDTIME      *gtime.Time `json:"eNDTIME"      ` // end_time
	TITLE        string      `json:"tITLE"        ` // title
	DESCRIPTION  string      `json:"dESCRIPTION"  ` // course discription
	TEACHER      string      `json:"tEACHER"      ` // teacher
	TYPE         int         `json:"tYPE"         ` // type
	PLACE        string      `json:"pLACE"        ` // place
	MAXMEMBERNUM int         `json:"mAXMEMBERNUM" ` // max member num
	NOWNUM       int         `json:"nOWNUM"       ` // now member num
}
