// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Credit is the golang structure for table credit.
type Credit struct {
	ID     int `json:"iD"     ` // ID
	USERID int `json:"uSERID" ` // User ID
	CREDIT int `json:"cREDIT" ` // Credit of User
}
