// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// FacilityScore is the golang structure for table facility_score.
type FacilityScore struct {
	FACILITYID int     `json:"fACILITYID" ` // Facility ID
	SCORE      float64 `json:"sCORE"      ` // Current Score
}
