// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// FacilityPlace is the golang structure for table facility_place.
type FacilityPlace struct {
	ID          int     `json:"iD"          ` // ID
	FACILITYID  int     `json:"fACILITYID"  ` // Facility ID
	NAME        string  `json:"nAME"        ` // Place Name
	DESCRIPTION string  `json:"dESCRIPTION" ` // Place Description
	COST        float64 `json:"cOST"        ` // Place order code
}
