// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Facility is the golang structure for table facility.
type Facility struct {
	ID          int    `json:"iD"          ` // Facility ID
	NAME        string `json:"nAME"        ` // Facility Name
	DESCRIPTION string `json:"dESCRIPTION" ` // Facility Description
	LOCATION    string `json:"lOCATION"    ` // Facility Location
	IMAGES      string `json:"iMAGES"      ` // Image urls
}
