// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Facility is the golang structure for table facility.
type Facility struct {
	Id          int     `json:"id"          ` //
	Name        string  `json:"name"        ` //
	Description string  `json:"description" ` //
	Location    string  `json:"location"    ` //
	Cost        float64 `json:"cost"        ` //
}
