// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure for table order.
type Order struct {
	ID          int         `json:"iD"          ` // ID
	USERID      int         `json:"uSERID"      ` // User id
	PLACEID     int         `json:"pLACEID"     ` // Place ID
	TIME        *gtime.Time `json:"tIME"        ` // Order Time
	STARTTIME   *gtime.Time `json:"sTARTTIME"   ` // Start time of the order
	ENDTIME     *gtime.Time `json:"eNDTIME"     ` // End time of the order
	PAYMENTTYPE int         `json:"pAYMENTTYPE" ` // Payment type
	AMOUNT      float64     `json:"aMOUNT"      ` // Amount of the order
	ORDERCODE   string      `json:"oRDERCODE"   ` // Order code
}
