// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Payment is the golang structure for table payment.
type Payment struct {
	ID          int    `json:"iD"          ` // ID
	WALLETID    string `json:"wALLETID"    ` // Wallet ID
	ORDERID     string `json:"oRDERID"     ` // Order ID
	PAYMENTCODE string `json:"pAYMENTCODE" ` // Payment code
	TIME        string `json:"tIME"        ` // Payment Time
}
