// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Payment is the golang structure for table payment.
type Payment struct {
	Id          int    `json:"id"          ` // ID
	WalletId    string `json:"walletId"    ` // Wallet ID
	OrderId     string `json:"orderId"     ` // Order ID
	PaymentCode string `json:"paymentCode" ` // Payment code
	Time        string `json:"time"        ` // Payment Time
}
