// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Receipt is the golang structure for table receipt.
type Receipt struct {
	ID          int    `json:"iD"          ` // ID
	ORDERID     string `json:"oRDERID"     ` // Order Id
	RECEIPTPATH string `json:"rECEIPTPATH" ` // PDF Receipt path
}
