// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Subscription is the golang structure for table subscription.
type Subscription struct {
	ID        int         `json:"iD"        ` // ID
	USERID    int         `json:"uSERID"    ` //
	STARTTIME *gtime.Time `json:"sTARTTIME" ` //
	ENDTIME   *gtime.Time `json:"eNDTIME"   ` //
}
