// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// TopicCommentApproves is the golang structure for table topic_comment_approves.
type TopicCommentApproves struct {
	ID         int `json:"iD"         ` // ID
	TYPE       int `json:"tYPE"       ` // TYPE
	UPDATETIME int `json:"uPDATETIME" ` // Update time
	USERID     int `json:"uSERID"     ` // USER_ID
	COMMENTID  int `json:"cOMMENTID"  ` // topic_comment_ID
}
