// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// TopicCommentApproves is the golang structure for table topic_comment_approves.
type TopicCommentApproves struct {
	Id         int `json:"id"         ` // ID
	Type       int `json:"type"       ` // TYPE
	UpdateTime int `json:"updateTime" ` // Update time
	UserId     int `json:"userId"     ` // USER_ID
	CommentId  int `json:"commentId"  ` // topic_comment_ID
}
