// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Topics is the golang structure for table topics.
type Topics struct {
	ID              int         `json:"iD"              ` // ID
	USERID          int         `json:"uSERID"          ` // USER_ID
	CONTENT         string      `json:"cONTENT"         ` // content
	TITLE           string      `json:"tITLE"           ` // title
	UPDATETIME      *gtime.Time `json:"uPDATETIME"      ` // time
	APPROVECOUNT    int         `json:"aPPROVECOUNT"    ` // Approve count
	DISAPPROVECOUNT int         `json:"dISAPPROVECOUNT" ` // Disapprove count
	IMAGES          string      `json:"iMAGES"          ` // Image urls
	VIDEOS          string      `json:"vIDEOS"          ` // Video urls
}
