// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicApproves is the golang structure for table topic_approves.
type TopicApproves struct {
	ID         int         `json:"iD"         ` // ID
	USERID     int         `json:"uSERID"     ` // USER_ID
	TOPICID    int         `json:"tOPICID"    ` // TOPIC_ID
	TYPE       int         `json:"tYPE"       ` // TYPE
	UPDATETIME *gtime.Time `json:"uPDATETIME" ` // create_time
}
