// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicComment is the golang structure for table topic_comment.
type TopicComment struct {
	ID              int         `json:"iD"              ` // ID
	USERID          int         `json:"uSERID"          ` // USER_ID
	TOPICID         int         `json:"tOPICID"         ` // TOPIC_ID
	PARENTCOMMENTID int         `json:"pARENTCOMMENTID" ` // Parent comment ID
	TITLE           string      `json:"tITLE"           ` // Comment_title
	CONTENT         string      `json:"cONTENT"         ` // Comment_conrtent
	APPROVE         string      `json:"aPPROVE"         ` // comment_approve
	DISAPPROVE      string      `json:"dISAPPROVE"      ` // comment_disapprove
	UPDATETIME      *gtime.Time `json:"uPDATETIME"      ` // creat_time
	IMAGES          string      `json:"iMAGES"          ` // Image urls
}
