// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       int         `json:"id"       ` //
	Username string      `json:"username" ` //
	Password string      `json:"password" ` //
	Avatar   string      `json:"avatar"   ` //
	Email    string      `json:"email"    ` //
	Phone    string      `json:"phone"    ` //
	Gender   string      `json:"gender"   ` //
	CreateAt string      `json:"createAt" ` //
	UpdateAt *gtime.Time `json:"updateAt" ` //
	Status   string      `json:"status"   ` //
	LoginAt  *gtime.Time `json:"loginAt"  ` //
	Role     int         `json:"role"     ` //
}
