// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WalletCard is the golang structure for table wallet_card.
type WalletCard struct {
	ID          int    `json:"iD"          ` // ID
	BANKID      int    `json:"bANKID"      ` // Bank ID of the card
	WALLETID    int    `json:"wALLETID"    ` // Wallet ID of the card
	CARDACCOUNT string `json:"cARDACCOUNT" ` // Card number
	PHONE       string `json:"pHONE"       ` // Phone of the card
	AMOUNT      string `json:"aMOUNT"      ` // Amount in the card
}
