// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Wallet is the golang structure for table wallet.
type Wallet struct {
	ID     int     `json:"iD"     ` // ID
	USERID int     `json:"uSERID" ` // User ID
	AMOUNT float64 `json:"aMOUNT" ` // Money amount
	STATUS int     `json:"sTATUS" ` // Wallet status
}
